new Notify ({
    status: 'success',
    title: 'Vše proběhlo úspěšně',
    text: 'Notify text lorem ipsum',
    effect: 'fade',
    speed: 300,
    customClass: '',
    customIcon: '',
    showIcon: true,
    showCloseButton: true,
    autoclose: true,
    autotimeout: 3000,
    gap: 20,
    distance: 20,
    type: 1,
    position: 'left bottom',
    customWrapper: '',
})